- README.md
Estou adorando seu curso de Git e GitHub.
Obrigado pela aula meu amigo Otacilio 💃
> Adicionando Marco Aurelio ao mural de alunos

- README.md
Parabéns pelas aulas de alta qualidade.
> Adicionado Felipe Brigagão ao mural de alunos

- README.md
Me adicionei na lista de alunos.
> Adição de mais um aluno

- README.md
Esta é a melhor aula do curso!!!
> Adicionando Allison Vasconcelos ao mural de alunos

- README.md
Estou facinado com tantas funcionalidades que o Git e GitHub nos proporcionam, são ferramentas valiosas para qualquer desenvolvedor
> Adicionei Sergio Bonatto ao mural de alunos

- README.md
Estou muito animado com o curso
> Adicionando Carlos Alberto ao mural de alunos

- README.md
Estou muito animado com o curso.
> Adicionando Vicente Monteiro ao mural de alunos da Platzi

- README.md
> Adicionando Lilian ao mural de alunos

- README.md
> adicioando Fabiano Bispo ao mural de alunos

- README.md
Olá. Sou Aliny Sousa, aluna do curso de Git e GitHub da Platzi e estou adorando o curso. Estou realizando todas as atividades.
> Adicionando Aliny Kelly Sousa ao mural de alunos

- README.md
Estou mt empolgada com tudo que venho aprendendo nesse curso!!
> adiconando apresentacao

- README.md
> Adicionando Stephanie Medeiros ao mural de alunos

- README.md
Estou muito animado com o curso!
> Adicionando Richard Lima ao mural de alunos

- README.md
Estou amando o curso de Git e GitHub! ❤️
> Adicionando Paulo Oliveira ao mural de alunos

- README.md
Olá Otacilio aceite por favor meu pull request. Obrigada
> Adicionando aluna Platzi Leda Gomes

- README.md
Estou gostando muito do curso de Git e GitHub!
> Adicionando Pedro Emanuel ao mural de alunos

- README.md
Muito obrigada pela oportunidade de participar desse curso. Amei d+
> Adicionando Jéssica Silvano ao mural de alunos

- README.md
Testando o pull request entre repositórios diferentes
> Adicionei Carolina Brito ao mural de alunos

- README.md
animado com o curso e as possibilidades do Git e GitHub
> Adicionando Daniel Camucatto ao mural de alunos 

- README.md
Muito animado com o curso de Git e GitHub.
> Adicionado Renato Maia ao mural de alunos

- README.md
> Adicionando Rose ao mural de alunos

- README.md
> Adicionando meu nome ao mural de alunos

- README.md
> Adicioando Luana Cristina ao mural de alunos.

- README.md
> Adicionando Fabio ao mural de alunos

- README.md
Olá! Estou adorando o curso. Obrigada.
> Adicionando meu nome à lista de alunos

- README.md
Estou muito animado com o curso!
> Adicionando Éric Vinícius ao mural de alunos

- README.md
Estou muito animado com o curso!
> Adicionando Rodolfo Bispo ao mural de alunos

- README.md
Estou muito animado com o curso :D
> Adicionando Lucas Moreira ao Mural de Alunos

- README.md
> Modificando o arquivo Readme, curso Platzi
